### ISSUE TITLE
[Bug Report]: Node Engine Version is fired

### ISSUE THREAD

**Issue by dangercris** [webdevnerdstuff/vue3-code-block#17]
### Bug description

IN your package json you have fired 

`"engines": {
		"node": "19.0.1"
},`

I use `--ignore-engines` and it works with node 18

### Steps to reproduce

1. yarn install

### Relevant log output

```shell
warning vscode-languageclient@7.0.0: The engine "vscode" appears to be invalid.
error vue3-code-block@2.1.1: The engine "node" is incompatible with this module. Expected version "19.0.1". Got "18.6.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by webdevnerdstuff** [comment]
I assume it works with some earlier versions of node, but I built it using `v19.0.1` and didn't test any earlier versions. Is there any issues with the component, or are you just reporting it works with `v18`?

**Comment by dangercris** [comment]
The problem is that it requires version 19.0.1 exactly, you should consider using ^19.0.1

**Comment by webdevnerdstuff** [comment]
Ah, I see what you are saying now. I'll try to push that update out this week sometime.
